Forms
Toka69/P6_SnowTricks pull request #36
Opened 2021-02-10 08:18 UTC by Toka69

Implementation of addition and edition forms.

2021-02-10 09:33 UTC, TBoileau requested changes

2021-02-10 09:33 UTC, TBoileau commented on src/Controller/TrickController.php
> +            $trick->setSlug(strtolower($slugger->slug($trick->getName())));
Si tu utilise le Slugger et donc le String Component, autant l'utiliser pour lowercase

2021-02-10 09:33 UTC, TBoileau commented on src/Controller/TrickController.php
> +            $trick->setCreatedDate(new DateTimeImmutable());
Tu peux déporter cette méthode dans le constructeur de ta classe.

2021-02-10 09:33 UTC, TBoileau commented on src/Controller/TrickController.php
> +            }
Créer le slug avant, et faire le test après.

Le FormError ne sert à rien car tu fais dans les cas une redirection. Il faut plutôt créer une [Validator](https://symfony.com/doc/current/validation/custom_constraint.html) custom.

2021-02-10 09:33 UTC, TBoileau commented on src/Controller/TrickController.php
> +            $trick->setSlug(strtolower($slugger->slug($trick->getName())));
Même remarque que sur le `add`

2021-02-10 09:33 UTC, TBoileau commented on src/Controller/TrickController.php
> +        $formView = $form->createView();
Pas besoin de créer une variable `formView`, car tu utilises un emplacement mémoire pour rien. Autant faire ton `createView` dans le return

2021-02-10 09:33 UTC, TBoileau commented on src/Controller/TrickController.php
> +        $formView = $form->createView();
Pas besoin de créer une variable `formView`, car tu utilises un emplacement mémoire pour rien. Autant faire ton `createView` dans le return

2021-02-10 09:33 UTC, TBoileau commented on src/Form/TrickType.php
> +                }
Depuis PHP 7.4, tu peux utiliser les fonctions fléchées : 
```php
'choice_label' => fn (Category $category) => u($category->getName())->toUpper(),
```

2021-02-10 09:33 UTC, TBoileau commented on templates/home/index.html.twig
> +                                                {% if app.user %}
Utilise plutôt la fonction `is_granted`
```twig
{% if is_granted("ROLE_USER") %}
```

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/add.html.twig
> +                {{ form_row(formView.category, {'attr': {'class': 'form-control'}}) }}
As-tu besoin de spécifier `form-control` quyand tu as déjà ajouter le thème `bootstrap_4_layout.html.twig` dans la configuration de `twig.yaml`.

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/add.html.twig
> +            <div class="form-group">
Attention supprimer le `form-group`, le `form-group` est une classe qui est censé être constituer d'un seul seul champs, de plus le `form_row`  va générer une `div.form-group`.

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/edit.html.twig
> +            {%  if app.user %}
Utilise plutôt la fonction `is_granted`
```twig
{% if is_granted("ROLE_USER") %}
```

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/edit.html.twig
> +        </div>
Inutile car tu vas gérer ça plus tard avec un `CollectionType`.

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/show.html.twig
> +                        {%  if app.user %}
Utilise plutôt la fonction `is_granted`
```twig
{% if is_granted("ROLE_USER") %}
```

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/show.html.twig
> +                {% if app.user %}
Utilise plutôt la fonction `is_granted`
```twig
{% if is_granted("ROLE_USER") %}
```

2021-02-10 09:33 UTC, TBoileau commented on templates/trick/show.html.twig
> +                                </form>
A gérer avec un `FormType`

2021-02-12 12:12 UTC, Toka69 commented on src/Controller/TrickController.php
> +            $trick->setCreatedDate(new DateTimeImmutable());
J'ouvre une nouvelle issue pour gérer ce point par la suite.

2021-02-12 12:13 UTC, Toka69 commented on src/Controller/TrickController.php
> +            $trick->setSlug(strtolower($slugger->slug($trick->getName())));
Sera traité avec l'issue ouverte spécifiquement.

2021-02-12 12:19 UTC, Toka69 commented on src/Controller/TrickController.php
> +            $trick->setSlug(strtolower($slugger->slug($trick->getName())));
Très bien j'ai mis en place le String Component complet pour utiliser  << u('')->lower() >>

2021-02-12 12:25 UTC, Toka69 commented on src/Controller/TrickController.php
> +            }
J'ai rajouter un $form->getErrors(true)->count() === 0 pour gérer la redirection. J'ouvre une issue pour le Validator, car j'ai tester un Custom Validator sur le field name mais les méthodes add et edit on des conditions différentes sur ce champ et qui font appel au repository (cf le commit [https://github.com/Toka69/P6_SnowTricks/commit/dbb69c9483fa2818ffa9dfb0e175807d1ca00fa4] ). Ce test ne fonctionnait que pour une condition. Donc mérite plus de recherche.

2021-02-12 12:27 UTC, Toka69 commented on src/Controller/TrickController.php
> +        $formView = $form->createView();
Fait.

2021-02-12 12:27 UTC, Toka69 commented on templates/trick/edit.html.twig
> +            {%  if app.user %}
Fait.

2021-02-12 12:28 UTC, Toka69 commented on templates/trick/show.html.twig
> +                        {%  if app.user %}
Fait.

2021-02-12 12:29 UTC, Toka69 commented on src/Controller/TrickController.php
> +        $formView = $form->createView();
Fait.

2021-02-12 12:29 UTC, Toka69 commented on templates/home/index.html.twig
> +                                                {% if app.user %}
fait

2021-02-12 12:29 UTC, Toka69 commented on templates/trick/add.html.twig
> +                {{ form_row(formView.category, {'attr': {'class': 'form-control'}}) }}
Fait.

2021-02-12 12:30 UTC, Toka69 commented on templates/trick/add.html.twig
> +            <div class="form-group">
Fait.

2021-02-12 12:30 UTC, Toka69 commented on templates/trick/edit.html.twig
> +            {%  if app.user %}
Fait.

2021-02-12 12:31 UTC, Toka69 commented on templates/trick/show.html.twig
> +                {% if app.user %}
Fait.

2021-02-12 21:38 UTC, Toka69 commented on templates/trick/show.html.twig
> +                                </form>
J'ai mis en place le formulaire fonctionnel pour les commentaires. Avec un CommentType et un @Assert\NotBlank sur le champ content.

2021-02-12 21:44 UTC, Toka69 commented on src/Form/TrickType.php
> +                }
Fait.

2021-02-12 21:49 UTC, Toka69 commented on templates/trick/edit.html.twig
> +        </div>
J'ouvre une nouvelle issue pour la gestion des CollectionType.

2021-02-14 10:12 UTC, merged