Frontend
Toka69/P6_SnowTricks pull request #48
Opened 2021-03-15 12:14 UTC by Toka69

Finalize the frontend, UI/UX :
- javascript
- css
- actions

2021-03-17 09:50 UTC, TBoileau requested changes

2021-03-17 09:50 UTC, TBoileau commented on src/Entity/Trick.php
> +            $cover->setlocation("../assets/img/cover.jpg");
Déplacer le fichier cover.jpg dans uploads

2021-03-17 09:50 UTC, TBoileau commented on src/Entity/Video.php
> +        }
On ne devrait pas avoir de DOM dans les entités

2021-03-17 09:50 UTC, TBoileau commented on templates/shared/_formPhoto.html.twig
> +                            <img id="previewImg-{{ photo.vars.id }}" src='{{ asset('/uploads/') ~ photo.vars.value.location }}' alt='photo' class='img-fluid littlePhoto' style='height: 150px'>
{{ asset('uploads/' ~ photo.vars.value.location) }}

2021-03-17 09:50 UTC, TBoileau commented on templates/shared/_formTrick.html.twig
> +            <img id="previewImg-{{ photo.vars.id }}" src='{{ asset("/uploads/") ~ photo.vars.value.location }}' alt='photo' class='img-fluid img-cover'>
{{ asset('uploads/' ~ photo.vars.value.location) }}

2021-03-18 18:05 UTC, Toka69 commented on src/Entity/Trick.php
> +            $cover->setlocation("../assets/img/cover.jpg");
Et j'ai simplifié getCover()

2021-03-19 12:44 UTC, Toka69 commented on src/Entity/Video.php
> +        }
J'ai enlever cette gestion de l'entité et j'ai créé un filtre twig, pour manipuler les différents type d'url youtube et dailymotion.

2021-03-19 13:03 UTC, Toka69 commented on templates/shared/_formPhoto.html.twig
> +                            <img id="previewImg-{{ photo.vars.id }}" src='{{ asset('/uploads/') ~ photo.vars.value.location }}' alt='photo' class='img-fluid littlePhoto' style='height: 150px'>
fait

2021-03-19 13:03 UTC, Toka69 commented on templates/shared/_formTrick.html.twig
> +            <img id="previewImg-{{ photo.vars.id }}" src='{{ asset("/uploads/") ~ photo.vars.value.location }}' alt='photo' class='img-fluid img-cover'>
Fait

2021-03-24 09:34 UTC, TBoileau requested changes

2021-03-24 09:34 UTC, TBoileau commented on src/Controller/TrickController.php
> +    public function delete(Trick $trick, EntityManagerInterface $em, SessionInterface $session): RedirectResponse
Supprimer le code mort

2021-03-24 09:34 UTC, TBoileau commented on templates/base.html.twig
> +            <link rel="stylesheet" href="/assets/css/lightbox.css">
utilise la fonction asset de twig

2021-03-24 10:35 UTC, Toka69 commented on src/Controller/TrickController.php
> +    public function delete(Trick $trick, EntityManagerInterface $em, SessionInterface $session): RedirectResponse
fait

2021-03-24 10:35 UTC, Toka69 commented on templates/base.html.twig
> +            <link rel="stylesheet" href="/assets/css/lightbox.css">
fait.

2021-03-25 13:32 UTC, merged