Refactorization v2
Toka69/P6_SnowTricks pull request #51
Opened 2021-04-06 21:04 UTC by Toka69

Move Controller's functions to services.

2021-04-07 08:57 UTC, TBoileau requested changes

2021-04-07 08:57 UTC, TBoileau commented on src/Controller/TrickController.php
> +    }
Injecter les services seulement dans les méthodes de tes contrôleurs, seulement là ou tu en as besoin

2021-04-07 08:57 UTC, TBoileau commented on src/Service/CommentLoader.php
> +        if ($currentComment + $numberComments >= count($this->commentRepository->getCommentsByTrickId($trick))){
On peut créer une méthode pour récupérer le nombre d'élément dans le repository

2021-04-07 08:57 UTC, TBoileau commented on src/Controller/HomeController.php
> +
Injecter directement dans la méthode du contrôleur qui a besoin de ce service

2021-04-07 21:14 UTC, Toka69 commented on src/Controller/TrickController.php
> +    }
Fait.

2021-04-07 21:16 UTC, Toka69 commented on src/Controller/HomeController.php
> +
Fait.

2021-04-08 19:13 UTC, Toka69 commented on src/Service/CommentLoader.php
> +        if ($currentComment + $numberComments >= count($this->commentRepository->getCommentsByTrickId($trick))){
fait

2021-04-10 09:19 UTC, merged