Fixes
Toka69/P6_SnowTricks pull request #53
Opened 2021-04-12 09:10 UTC by Toka69

Some fixes to finalize the project.

2021-04-13 06:56 UTC, TBoileau requested changes

2021-04-13 06:56 UTC, TBoileau commented on src/Security/UserChecker.php
> +        }
As tu tester sans la request ? La request n'a vraiment rien à faire là, si tu arrive dans le checker c'est que tu es forcément entrain de te connecté et donc sur login_check

2021-04-13 07:02 UTC, Toka69 commented on src/Security/UserChecker.php
> +        }
Merci. La route login-check ne sert qu'au système login link de SF 5.2 et il ne faut pas que cette exception soit levée sur cette route là sinon on ne peut jamais valider le compte. La route pour la connexion classique est security_login.

2021-04-14 08:26 UTC, TBoileau commented on src/Security/UserChecker.php
> +        }
Et si tu le fais dans le PostAuth ?

2021-04-14 08:30 UTC, TBoileau approved these changes

2021-04-14 19:32 UTC, merged